# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('trabajo', models.CharField(max_length=100)),
                ('foto', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='charla',
            name='speakers',
            field=models.ManyToManyField(to='slud.Speaker'),
        ),
    ]
