# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 22:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('slud', '0002_charla_timefecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charla',
            name='timefecha',
        ),
        migrations.AddField(
            model_name='charla',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2016, 10, 1, 22, 36, 19, 973947, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charla',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2016, 10, 1, 22, 36, 28, 583675, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
