# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slud', '0003_auto_20161001_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='speaker',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
